update Rust edition to 2024, migrate to makefile, upload lockfile
Signed-off-by: usamoi <usamoi@outlook.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Release
+name: Publish
 
 on:
   release:
@@ -21,7 +21,7 @@ jobs:
     steps:
       - name: Semver
         id: semver
-        uses: actions/github-script@v7
+        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
         with:
           script: |
             const tag = "${{ github.event.inputs.tag }}" || "${{ github.event.release.tag_name }}";
@@ -41,27 +41,97 @@ jobs:
       matrix:
         version: ["14", "15", "16", "17", "18"]
         arch: ["x86_64", "aarch64"]
-    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
+    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-22.04' || 'ubuntu-22.04-arm' }}
 
     env:
-      CARGO_TERM_COLOR: always
-      RUST_BACKTRACE: 1
+      RUSTUP_AUTO_INSTALL: "0"
       RUSTFLAGS: "-Dwarnings"
-      SEMVER: ${{ needs.semver.outputs.SEMVER }}
-      VERSION: ${{ matrix.version }}
-      ARCH: ${{ matrix.arch }}
-      PLATFORM: ${{ matrix.arch == 'x86_64' && 'amd64' || 'arm64' }}
+      CARGO_TERM_COLOR: "always"
+      RUST_BACKTRACE: "1"
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
       - name: Set up Environment
-        run: ./tools/setup.sh ${{ matrix.version }}
+        run: |
+          sudo apt-get update
+
+      - name: Install Rust
+        run: rustup update
+
+      - name: Install PostgreSQL
+        run: |
+          sudo apt-get remove -y '^postgres.*' '^libpq.*'
+          sudo apt-get purge -y '^postgres.*' '^libpq.*'
+
+          sudo apt-get install -y --no-install-recommends postgresql-common
+          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
+          sudo apt-get install -y --no-install-recommends postgresql-server-dev-${{ matrix.version }}
+
+          pg_config
+
+      - name: Checkout
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+
       - name: Build
-        run: ./tools/package.sh
-      - name: Upload Artifacts
+        run: |
+          grep -q "default_version = '${{ needs.semver.outputs.SEMVER }}'" pg_tokenizer.control || exit 1
+          make build
+
+      - name: Package (binary package)
         env:
           GH_TOKEN: ${{ github.token }}
+          SEMVER: ${{ needs.semver.outputs.SEMVER }}
+          VERSION: ${{ matrix.version }}
         run: |
-          gh release upload --clobber $SEMVER ./build/postgresql-${VERSION}-pg-tokenizer_${SEMVER}-1_${PLATFORM}.deb
-          gh release upload --clobber $SEMVER ./build/postgresql-${VERSION}-pg-tokenizer_${SEMVER}_${ARCH}-linux-gnu.zip
+          ARCH=$(uname -m)
+          (cd ./build && zip -r ~/postgresql-${VERSION}-pg-tokenizer_${SEMVER}_${ARCH}-linux-gnu.zip .)
+          gh release upload --clobber $SEMVER ~/postgresql-${VERSION}-pg-tokenizer_${SEMVER}_${ARCH}-linux-gnu.zip
+
+      - name: Package (debian package)
+        env:
+          GH_TOKEN: ${{ github.token }}
+          SEMVER: ${{ needs.semver.outputs.SEMVER }}
+          VERSION: ${{ matrix.version }}
+        run: |
+          make DESTDIR="~/debian" install
+          ARCH=$(uname -m)
+          PLATFORM=$(dpkg --print-architecture)
+          mkdir -p ~/debian/DEBIAN
+          echo "Package: postgresql-${VERSION}-pg-tokenizer
+          Version: ${SEMVER}-1
+          Depends: postgresql-${VERSION}, libgcc-s1, libc6 (>= 2.35)
+          Section: database
+          Priority: optional
+          Architecture: ${PLATFORM}
+          Maintainer: Tensorchord <support@tensorchord.ai>
+          Description: Tokenizer plugin for PostgreSQL
+          Homepage: https://vectorchord.ai/
+          License: Apache-2.0" \
+          > ~/debian/DEBIAN/control
+          (cd ~/debian && find usr -type f -print0 | xargs -0 md5sum) > ~/debian/DEBIAN/md5sums
+          dpkg-deb --root-owner-group -Zxz --build ~/debian ~/postgresql-${VERSION}-pg-tokenizer_${SEMVER}-1_${PLATFORM}.deb
+          gh release upload --clobber $SEMVER ~/postgresql-${VERSION}-pg-tokenizer_${SEMVER}-1_${PLATFORM}.deb
+
+#  pgxn:
+#    runs-on: "ubuntu-latest"
+#    needs: ["semver", "build"]
+#
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+#
+#      - name: Upload
+#        env:
+#          SEMVER: ${{ needs.semver.outputs.SEMVER }}
+#          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
+#        run: |
+#          mkdir -p ./build
+#
+#          sed -e "s/@DISTVERSION@/${SEMVER}/g" META.json.in > META.json
+#          git archive --format zip --prefix "pg_tokenizer-${SEMVER}/" --add-file META.json -o "./build/pg_tokenizer--${SEMVER}.zip" HEAD
+#
+#          curl --fail -sS \
+#            --user "tensorchord:${PGXN_PASSWORD}" \
+#            -F "submit=Release It!" \
+#            -F "archive=@./build/pg_tokenizer--${SEMVER}.zip" \
+#            -H "X-Requested-With: XMLHttpRequest" \
+#            https://manager.pgxn.org/upload
